#!/bin/bash
### route PROV1
/sbin/ip route delete default via 10.0.2.2 dev eth0 proto dhcp
/sbin/ip route add default via 10.0.2.2 dev eth0 proto dhcp metric 100

/sbin/ip route delete 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 
/sbin/ip route add 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100

/sbin/ip route add default via 10.0.2.2 table 101
/sbin/ip route add 10.0.2.0/24 dev eth0 src 10.0.2.15 table 101


### route PROV2
/sbin/ip route delete default via 172.18.0.5 dev eth1 proto static
/sbin/ip route add default via 172.18.0.5 dev eth1 proto static metric 102

/sbin/ip route delete 172.18.0.0/24 dev eth1 proto kernel scope link src 172.18.0.4
/sbin/ip route add 172.18.0.0/24 dev eth1 proto kernel scope link src 172.18.0.4 metric 102

/sbin/ip route add default via 172.18.0.5 table 102
/sbin/ip route add 172.18.0.0/24 dev eth1 src 172.18.0.4 table 102
